@startuml
Admin -> Warehouse_mapper: achieve: remove(item(id(I), quantity(Q)))
Warehouse_mapper -> Admin: failure: remove(item(id(I), quantity(Q)))
@enduml

@startuml
Admin -> Warehouse_mapper: achieve: remove(item(id(I), quantity(Q)))
Warehouse_mapper -> Admin: confirm: remove(item(id(I), quantity(Q)))[position(rack(3),shelf(4),quantity(5)), ...]
@enduml