@startuml class_diagram
class Communicator {
    {method} sendMessage(message: ACLMessage)
    {method} sendMessage(\n\
        message: ACLMessage,\n\
        retryOnFailure: boolean,\n\
        mapTo: ACLMessage -> T
    ): Future<T>
}
class jade.core.Agent {
    {method} setup()
}
class user.Agent {
    {method} shutdown()
    {method} shopItems(): Future<Collection<QuantityItem>>
    {method} placeOrder(user: User, items: Collection<QuantityItem>)
    {method} orders(user: User): Future<Collection<InfoOrder>>
}

user.Agent      -|> Communicator
Communicator    -|> jade.core.Agent
@enduml
